// Code generated by "stringer -type=AdministrativeRoleMemberAction -trimprefix AdministrativeRoleMemberAction"; DO NOT EDIT.

package dvls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AdministrativeRoleMemberActionAdd-0]
	_ = x[AdministrativeRoleMemberActionDelete-1]
}

const _AdministrativeRoleMemberAction_name = "AddDelete"

var _AdministrativeRoleMemberAction_index = [...]uint8{0, 3, 9}

func (i AdministrativeRoleMemberAction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AdministrativeRoleMemberAction_index)-1 {
		return "AdministrativeRoleMemberAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AdministrativeRoleMemberAction_name[_AdministrativeRoleMemberAction_index[idx]:_AdministrativeRoleMemberAction_index[idx+1]]
}
