// Code generated by "stringer -type=AdministrativeRoleScopeType -trimprefix AdministrativeRoleScope"; DO NOT EDIT.

package dvls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AdministrativeRoleScopeGlobal-0]
	_ = x[AdministrativeRoleScopeOrganizationalUnit-1]
	_ = x[AdministrativeRoleScopeVault-2]
	_ = x[AdministrativeRoleScopeGateway-3]
	_ = x[AdministrativeRoleScopePamProvider-4]
}

const _AdministrativeRoleScopeType_name = "GlobalOrganizationalUnitVaultGatewayPamProvider"

var _AdministrativeRoleScopeType_index = [...]uint8{0, 6, 24, 29, 36, 47}

func (i AdministrativeRoleScopeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AdministrativeRoleScopeType_index)-1 {
		return "AdministrativeRoleScopeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AdministrativeRoleScopeType_name[_AdministrativeRoleScopeType_index[idx]:_AdministrativeRoleScopeType_index[idx+1]]
}
