// Code generated by "stringer -type=AdministrativeRoleAssigneeType -trimprefix AdministrativeRoleAssignee"; DO NOT EDIT.

package dvls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AdministrativeRoleAssigneeUser-0]
	_ = x[AdministrativeRoleAssigneeApplication-1]
	_ = x[AdministrativeRoleAssigneeUserGroup-2]
}

const _AdministrativeRoleAssigneeType_name = "UserApplicationUserGroup"

var _AdministrativeRoleAssigneeType_index = [...]uint8{0, 4, 15, 24}

func (i AdministrativeRoleAssigneeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AdministrativeRoleAssigneeType_index)-1 {
		return "AdministrativeRoleAssigneeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AdministrativeRoleAssigneeType_name[_AdministrativeRoleAssigneeType_index[idx]:_AdministrativeRoleAssigneeType_index[idx+1]]
}
