package dvls

//go:generate stringer -type=SaveResult -trimprefix SaveResult
type SaveResult uint8

const (
	SaveResultError SaveResult = iota
	SaveResultSuccess
	SaveResultAccessDenied
	SaveResultInvalidData
	SaveResultAlreadyExists
	SaveResultMaximumReached
	SaveResultNotFound
	SaveResultLicenseExpired
	SaveResultUnknown
	SaveResultTwoFactorTypeNotConfigured
	SaveResultWebApiRedirectToLogin
	SaveResultDuplicateLoginEmail
)

//go:generate stringer -type=UserAuthenticationType -trimprefix UserAuthentication
type UserAuthenticationType uint8

const (
	UserAuthenticationBuiltin UserAuthenticationType = iota
	UserAuthenticationLocalWindows
	UserAuthenticationSqlServer
	UserAuthenticationDomain
	UserAuthenticationOffice365
	UserAuthenticationNone
	UserAuthenticationCloud
	UserAuthenticationLegacy
	UserAuthenticationAzureAD
	UserAuthenticationApplication
	UserAuthenticationOkta
)

//go:generate stringer -type=ServerLoginResult -trimprefix ServerLogin
type ServerLoginResult uint8

const (
	ServerLoginError ServerLoginResult = iota
	ServerLoginSuccess
	ServerLoginInvalidUserNamePassword
	ServerLoginInvalidDataSource
	ServerLoginDisabledDataSource
	ServerLoginInvalidSubscription
	ServerLoginTooManyUserForTheLicense
	ServerLoginExpiredSubscription
	ServerLoginInGracePeriod
	ServerLoginDisabledUser
	ServerLoginUserNotFound
	ServerLoginLockedUser
	ServerLoginNotApprovedUser
	ServerLoginBlackListed
	ServerLoginInvalidIP
	ServerLoginUnableToCreateUser
	ServerLoginTwoFactorTypeNotConfigured
	ServerLoginTwoFactorTypeActivatedNotAllowedClientSide
	ServerLoginDomainNotTrusted
	ServerLoginUserDoesNotBelongToDefaultDomain
	ServerLoginInvalidGeoIP
	ServerLoginTwoFactorIsRequired
	ServerLoginTwoFactorPreconfigured
	ServerLoginTwoFactorSecondStepIsRequired
	ServerLoginTwoFactorUserIsDenied
	ServerLoginTwoFactorSmsSended
	ServerLoginTwoFactorTimeout
	ServerLoginTwoFactorUserLockedOut
	ServerLoginTwoFactorUserFraud
	ServerLoginTwoFactorUserEmailNotConfigured
	ServerLoginTwoFactorUserSmsNotConfigured
	ServerLoginNotInTrustedGroup
	ServerLoginServerNotResponding
	ServerLoginNotAccessToApplication
	ServerLoginDirectoryNotResponding
	ServerLoginWindowsAuthenticationFailure
	ServerLoginForcePasswordChange
	ServerLoginTwoFactorInvalid
	ServerLoginOutsideValidUsageTimePeriod
)

type EntryType string

const (
	EntryTypeCredential EntryType = "Credential"
)

type EntrySubType string

const (
	EntrySubTypeDefault EntrySubType = ""
)
