package dvls

//go:generate stringer -type=UserAuthenticationType -trimprefix UserAuthentication
type UserAuthenticationType uint8

const (
	UserAuthenticationBuiltin UserAuthenticationType = iota
	UserAuthenticationLocalWindows
	UserAuthenticationSqlServer
	UserAuthenticationDomain
	UserAuthenticationOffice365
	UserAuthenticationNone
	UserAuthenticationCloud
	UserAuthenticationLegacy
	UserAuthenticationAzureAD
	UserAuthenticationApplication
	UserAuthenticationOkta
)

//go:generate stringer -type=ServerLoginResult -trimprefix ServerLogin
type ServerLoginResult uint8

const (
	ServerLoginError ServerLoginResult = iota
	ServerLoginSuccess
	ServerLoginInvalidUserNamePassword
	ServerLoginInvalidDataSource
	ServerLoginDisabledDataSource
	ServerLoginInvalidSubscription
	ServerLoginTooManyUserForTheLicense
	ServerLoginExpiredSubscription
	ServerLoginInGracePeriod
	ServerLoginDisabledUser
	ServerLoginUserNotFound
	ServerLoginLockedUser
	ServerLoginNotApprovedUser
	ServerLoginBlackListed
	ServerLoginInvalidIP
	ServerLoginUnableToCreateUser
	ServerLoginTwoFactorTypeNotConfigured
	ServerLoginTwoFactorTypeActivatedNotAllowedClientSide
	ServerLoginDomainNotTrusted
	ServerLoginUserDoesNotBelongToDefaultDomain
	ServerLoginInvalidGeoIP
	ServerLoginTwoFactorIsRequired
	ServerLoginTwoFactorPreconfigured
	ServerLoginTwoFactorSecondStepIsRequired
	ServerLoginTwoFactorUserIsDenied
	ServerLoginTwoFactorSmsSended
	ServerLoginTwoFactorTimeout
	ServerLoginTwoFactorUserLockedOut
	ServerLoginTwoFactorUserFraud
	ServerLoginTwoFactorUserEmailNotConfigured
	ServerLoginTwoFactorUserSmsNotConfigured
	ServerLoginNotInTrustedGroup
	ServerLoginServerNotResponding
	ServerLoginNotAccessToApplication
	ServerLoginDirectoryNotResponding
	ServerLoginWindowsAuthenticationFailure
	ServerLoginForcePasswordChange
	ServerLoginTwoFactorInvalid
	ServerLoginOutsideValidUsageTimePeriod
)

//go:generate stringer -type=ServerConnectionType -trimprefix ServerConnection
type ServerConnectionType uint8

const (
	ServerConnectionUndefined ServerConnectionType = iota
	ServerConnectionRDPConfigured
	ServerConnectionRDPFilename
	ServerConnectionCommandLine
	ServerConnectionVNC
	ServerConnectionWebBrowser
	ServerConnectionLogMeIn
	ServerConnectionTeamViewer
	ServerConnectionPutty
	ServerConnectionFtp
	ServerConnectionVirtualPC
	ServerConnectionRadmin
	ServerConnectionDameware
	ServerConnectionVMWare
	ServerConnectionPCAnywhere
	ServerConnectionICA
	ServerConnectionXWindow
	ServerConnectionHyperV
	ServerConnectionAddOn
	ServerConnectionRemoteAssistance
	ServerConnectionVPN
	ServerConnectionVirtualBox
	ServerConnectionVMRC
	ServerConnectionXenServer
	ServerConnectionWindowsVirtualPC
	ServerConnectionGroup
	ServerConnectionCredential
	ServerConnectionHpRgs
	ServerConnectionDesktone
	ServerConnectionApplicationTool
	ServerConnectionSessionTool
	ServerConnectionContact
	ServerConnectionDataEntry
	ServerConnectionDataReport
	ServerConnectionAgent
	ServerConnectionComputer
	ServerConnectionDropBox
	ServerConnectionS3
	ServerConnectionAzureStorage
	ServerConnectionCitrixWeb
	ServerConnectionPowerShell
	ServerConnectionHostSessionTool
	ServerConnectionShortcut
	ServerConnectionIntelAMT
	ServerConnectionAzure
	ServerConnectionDocument
	ServerConnectionVMWareConsole
	ServerConnectionInventoryReport
	ServerConnectionSkyDrive
	ServerConnectionScreenConnect
	ServerConnectionAzureTableStorage
	ServerConnectionAzureQueueStorage
	ServerConnectionTemplateGroup
	ServerConnectionHost
	ServerConnectionDatabase
	ServerConnectionCustomer
	ServerConnectionADConsole
	ServerConnectionAws
	ServerConnectionSNMPReport
	ServerConnectionSync
	ServerConnectionGateway
	ServerConnectionPlayList
	ServerConnectionTerminalConsole
	ServerConnectionPSExec
	ServerConnectionAppleRemoteDesktop
	ServerConnectionSpiceworks
	ServerConnectionDeskRoll
	ServerConnectionSecureCRT
	ServerConnectionIterm
	ServerConnectionSheet
	ServerConnectionSplunk
	ServerConnectionPortForward
	ServerConnectionTeamViewerConsole
	ServerConnectionScreenHero
	ServerConnectionTelnet
	ServerConnectionSerial
	ServerConnectionSSHTunnel
	ServerConnectionSSHShell
	ServerConnectionResetPassword
	ServerConnectionWayk
	ServerConnectionControlUp
	ServerConnectionDataSource
	ServerConnectionChromeRemoteDesktop
	ServerConnectionRDCommander
	ServerConnectionIDrac
	ServerConnectionIlo
	ServerConnectionWebDav
	ServerConnectionBeyondTrustPasswordSafeConsole
	ServerConnectionDevolutionsProxy
	ServerConnectionFtpNative
	ServerConnectionPowerShellRemoteConsole
	ServerConnectionProxyTunnel
	ServerConnectionRoot
	ServerConnectionBeyondTrustPasswordSafe
	ServerConnectionFileExplorer
	ServerConnectionScp
	ServerConnectionSftp
	ServerConnectionAzureBlobStorage
	ServerConnectionTFtp
	ServerConnectionGoToAssist
	ServerConnectionIPTable
	ServerConnectionHub
	ServerConnectionGoogleDrive
	ServerConnectionGoogleCloud
	ServerConnectionNoVNC
	ServerConnectionSplashtop
	ServerConnectionJumpDesktop
	ServerConnectionBoxNet
	ServerConnectionMSPAnywhere
	ServerConnectionRepository
	ServerConnectionCyberArkPSM
	ServerConnectionCloudBerryRemoteAssistant
	ServerConnectionITGlue
	ServerConnectionSmartFolder
	ServerConnectionCyberArkJump
	ServerConnectionWindowsAdminCenter
	ServerConnectionDevolutionsGateway
	ServerConnectionWaykDenConsole
	ServerConnectionRDGatewayConsole
	ServerConnectionCyberArkDashboard
	ServerConnectionDVLSPamDashboard
	ServerConnectionSMB
	ServerConnectionAppleRemoteManagement
	ServerConnectionRustDesk
	ServerConnectionPAM
	ServerConnectionITManager
	ServerConnectionCustomImage
)

type ServerConnectionSubType string

const (
	ServerConnectionSubTypeDefault ServerConnectionSubType = "Default"
)
