// Code generated by "stringer -type=SecurityRoleRight -trimprefix SecurityRoleRight"; DO NOT EDIT.

package dvls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SecurityRoleRightView-0]
	_ = x[SecurityRoleRightViewPassword-1]
	_ = x[SecurityRoleRightAdd-2]
	_ = x[SecurityRoleRightDelete-3]
	_ = x[SecurityRoleRightEdit-4]
	_ = x[SecurityRoleRightEditStatus-5]
	_ = x[SecurityRoleRightEditDescription-6]
	_ = x[SecurityRoleRightEditSecurity-7]
	_ = x[SecurityRoleRightPasswordHistory-8]
	_ = x[SecurityRoleRightConnectionHistory-9]
	_ = x[SecurityRoleRightRemoteTools-10]
	_ = x[SecurityRoleRightAttachment-11]
	_ = x[SecurityRoleRightEditAttachment-12]
	_ = x[SecurityRoleRightInventory-13]
	_ = x[SecurityRoleRightViewLogs-14]
	_ = x[SecurityRoleRightHandbook-15]
	_ = x[SecurityRoleRightEditHandbook-16]
	_ = x[SecurityRoleRightWebManagementTools-17]
	_ = x[SecurityRoleRightConsoleManagementTools-18]
	_ = x[SecurityRoleRightMacroScriptTools-19]
	_ = x[SecurityRoleRightMacroScriptToolsEntry-20]
	_ = x[SecurityRoleRightEditPassword-21]
	_ = x[SecurityRoleRightExecute-22]
	_ = x[SecurityRoleRightViewSessionRecording-23]
	_ = x[SecurityRoleRightViewInformation-24]
	_ = x[SecurityRoleRightExport-25]
	_ = x[SecurityRoleRightEditInformation-26]
	_ = x[SecurityRoleRightMove-27]
	_ = x[SecurityRoleRightDeleteHandbook-28]
	_ = x[SecurityRoleRightViewSensitiveInformation-29]
	_ = x[SecurityRoleRightResetPassword-30]
	_ = x[SecurityRoleRightApproveCheckoutRequest-31]
	_ = x[SecurityRoleRightForceCheckin-32]
	_ = x[SecurityRoleRightCheckout-33]
	_ = x[SecurityRoleRightReadLogs-34]
	_ = x[SecurityRoleRightSealed-35]
	_ = x[SecurityRoleRightEditVPNSSHGatewayConfiguration-36]
	_ = x[SecurityRoleRightEditSessionRecordingConfiguration-37]
}

const _SecurityRoleRight_name = "ViewViewPasswordAddDeleteEditEditStatusEditDescriptionEditSecurityPasswordHistoryConnectionHistoryRemoteToolsAttachmentEditAttachmentInventoryViewLogsHandbookEditHandbookWebManagementToolsConsoleManagementToolsMacroScriptToolsMacroScriptToolsEntryEditPasswordExecuteViewSessionRecordingViewInformationExportEditInformationMoveDeleteHandbookViewSensitiveInformationResetPasswordApproveCheckoutRequestForceCheckinCheckoutReadLogsSealedEditVPNSSHGatewayConfigurationEditSessionRecordingConfiguration"

var _SecurityRoleRight_index = [...]uint16{0, 4, 16, 19, 25, 29, 39, 54, 66, 81, 98, 109, 119, 133, 142, 150, 158, 170, 188, 210, 226, 247, 259, 266, 286, 301, 307, 322, 326, 340, 364, 377, 399, 411, 419, 427, 433, 463, 496}

func (i SecurityRoleRight) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SecurityRoleRight_index)-1 {
		return "SecurityRoleRight(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SecurityRoleRight_name[_SecurityRoleRight_index[idx]:_SecurityRoleRight_index[idx+1]]
}
