// Code generated by "stringer -type=SecurityRoleOverride -trimprefix SecurityRoleOverride"; DO NOT EDIT.

package dvls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SecurityRoleOverrideDefault-0]
	_ = x[SecurityRoleOverrideCustom-1]
	_ = x[SecurityRoleOverrideInherited-2]
	_ = x[SecurityRoleOverrideEveryone-3]
	_ = x[SecurityRoleOverrideNever-4]
	_ = x[SecurityRoleOverrideCustomInherited-5]
}

const _SecurityRoleOverride_name = "DefaultCustomInheritedEveryoneNeverCustomInherited"

var _SecurityRoleOverride_index = [...]uint8{0, 7, 13, 22, 30, 35, 50}

func (i SecurityRoleOverride) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SecurityRoleOverride_index)-1 {
		return "SecurityRoleOverride(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SecurityRoleOverride_name[_SecurityRoleOverride_index[idx]:_SecurityRoleOverride_index[idx+1]]
}
