// Code generated by "stringer -type=ServerLoginResult -trimprefix ServerLogin"; DO NOT EDIT.

package dvls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerLoginError-0]
	_ = x[ServerLoginSuccess-1]
	_ = x[ServerLoginInvalidUserNamePassword-2]
	_ = x[ServerLoginInvalidDataSource-3]
	_ = x[ServerLoginDisabledDataSource-4]
	_ = x[ServerLoginInvalidSubscription-5]
	_ = x[ServerLoginTooManyUserForTheLicense-6]
	_ = x[ServerLoginExpiredSubscription-7]
	_ = x[ServerLoginInGracePeriod-8]
	_ = x[ServerLoginDisabledUser-9]
	_ = x[ServerLoginUserNotFound-10]
	_ = x[ServerLoginLockedUser-11]
	_ = x[ServerLoginNotApprovedUser-12]
	_ = x[ServerLoginBlackListed-13]
	_ = x[ServerLoginInvalidIP-14]
	_ = x[ServerLoginUnableToCreateUser-15]
	_ = x[ServerLoginTwoFactorTypeNotConfigured-16]
	_ = x[ServerLoginTwoFactorTypeActivatedNotAllowedClientSide-17]
	_ = x[ServerLoginDomainNotTrusted-18]
	_ = x[ServerLoginUserDoesNotBelongToDefaultDomain-19]
	_ = x[ServerLoginInvalidGeoIP-20]
	_ = x[ServerLoginTwoFactorIsRequired-21]
	_ = x[ServerLoginTwoFactorPreconfigured-22]
	_ = x[ServerLoginTwoFactorSecondStepIsRequired-23]
	_ = x[ServerLoginTwoFactorUserIsDenied-24]
	_ = x[ServerLoginTwoFactorSmsSended-25]
	_ = x[ServerLoginTwoFactorTimeout-26]
	_ = x[ServerLoginTwoFactorUserLockedOut-27]
	_ = x[ServerLoginTwoFactorUserFraud-28]
	_ = x[ServerLoginTwoFactorUserEmailNotConfigured-29]
	_ = x[ServerLoginTwoFactorUserSmsNotConfigured-30]
	_ = x[ServerLoginNotInTrustedGroup-31]
	_ = x[ServerLoginServerNotResponding-32]
	_ = x[ServerLoginNotAccessToApplication-33]
	_ = x[ServerLoginDirectoryNotResponding-34]
	_ = x[ServerLoginWindowsAuthenticationFailure-35]
	_ = x[ServerLoginForcePasswordChange-36]
	_ = x[ServerLoginTwoFactorInvalid-37]
	_ = x[ServerLoginOutsideValidUsageTimePeriod-38]
}

const _ServerLoginResult_name = "ErrorSuccessInvalidUserNamePasswordInvalidDataSourceDisabledDataSourceInvalidSubscriptionTooManyUserForTheLicenseExpiredSubscriptionInGracePeriodDisabledUserUserNotFoundLockedUserNotApprovedUserBlackListedInvalidIPUnableToCreateUserTwoFactorTypeNotConfiguredTwoFactorTypeActivatedNotAllowedClientSideDomainNotTrustedUserDoesNotBelongToDefaultDomainInvalidGeoIPTwoFactorIsRequiredTwoFactorPreconfiguredTwoFactorSecondStepIsRequiredTwoFactorUserIsDeniedTwoFactorSmsSendedTwoFactorTimeoutTwoFactorUserLockedOutTwoFactorUserFraudTwoFactorUserEmailNotConfiguredTwoFactorUserSmsNotConfiguredNotInTrustedGroupServerNotRespondingNotAccessToApplicationDirectoryNotRespondingWindowsAuthenticationFailureForcePasswordChangeTwoFactorInvalidOutsideValidUsageTimePeriod"

var _ServerLoginResult_index = [...]uint16{0, 5, 12, 35, 52, 70, 89, 113, 132, 145, 157, 169, 179, 194, 205, 214, 232, 258, 300, 316, 348, 360, 379, 401, 430, 451, 469, 485, 507, 525, 556, 585, 602, 621, 643, 665, 693, 712, 728, 755}

func (i ServerLoginResult) String() string {
	if i < 0 || i >= ServerLoginResult(len(_ServerLoginResult_index)-1) {
		return "ServerLoginResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerLoginResult_name[_ServerLoginResult_index[i]:_ServerLoginResult_index[i+1]]
}
