// Code generated by "stringer -type=UserAuthenticationType -trimprefix UserAuthentication"; DO NOT EDIT.

package dvls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserAuthenticationBuiltin-0]
	_ = x[UserAuthenticationLocalWindows-1]
	_ = x[UserAuthenticationSqlServer-2]
	_ = x[UserAuthenticationDomain-3]
	_ = x[UserAuthenticationOffice365-4]
	_ = x[UserAuthenticationNone-5]
	_ = x[UserAuthenticationCloud-6]
	_ = x[UserAuthenticationLegacy-7]
	_ = x[UserAuthenticationAzureAD-8]
	_ = x[UserAuthenticationApplication-9]
	_ = x[UserAuthenticationOkta-10]
}

const _UserAuthenticationType_name = "BuiltinLocalWindowsSqlServerDomainOffice365NoneCloudLegacyAzureADApplicationOkta"

var _UserAuthenticationType_index = [...]uint8{0, 7, 19, 28, 34, 43, 47, 52, 58, 65, 76, 80}

func (i UserAuthenticationType) String() string {
	if i < 0 || i >= UserAuthenticationType(len(_UserAuthenticationType_index)-1) {
		return "UserAuthenticationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserAuthenticationType_name[_UserAuthenticationType_index[i]:_UserAuthenticationType_index[i+1]]
}
