// Code generated by "stringer -type=UserGroupType -trimprefix UserGroupType"; DO NOT EDIT.

package dvls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserGroupTypeActiveDirectory-0]
	_ = x[UserGroupTypeCustom-1]
	_ = x[UserGroupTypeOffice365-2]
	_ = x[UserGroupTypeOkta-3]
	_ = x[UserGroupTypePingOne-4]
}

const _UserGroupType_name = "ActiveDirectoryCustomOffice365OktaPingOne"

var _UserGroupType_index = [...]uint8{0, 15, 21, 30, 34, 41}

func (i UserGroupType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UserGroupType_index)-1 {
		return "UserGroupType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserGroupType_name[_UserGroupType_index[idx]:_UserGroupType_index[idx+1]]
}
